p1=input('Digite para informações sobre:')
tipo=(type(p1))
print('Tipo:{}'.format(tipo))
numerico=(p1.isnumeric())
print('Numerico:{}.'.format(numerico))
alfabetico=(p1.isalpha())
print('Alfabetico:{}'.format(alfabetico))
letrasm=(p1.isupper())
print('Só tem Letras Maiusculas:{}'.format(letrasm))
